 # -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-10 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Header')),
                ('completed', models.BooleanField(verbose_name='Status')),
            ],
        ),
    ]
